package:
  name: q2-diversity
  version: {{ PLUGIN_VERSION }}
source:
  path: ..
build:
  script: make install
requirements:
  build:
  - nodejs
  - setuptools
  - versioningit
  host:
  - python {{ python }}
  - setuptools
  - versioningit
  - wheel
  run:
  - python {{ python }}
  - numpy
  - scipy {{ scipy }}
  - pandas {{ pandas }}
  - statsmodels
  - seaborn
  - ipywidgets
  - scikit-bio {{ scikit_bio }}
  - scikit-learn {{ scikit_learn }}
  - psutil
  - natsort
  - biom-format {{ biom_format }}
  - qiime2 {{ qiime2_epoch }}.*
  - q2templates {{ qiime2_epoch }}.*
  - q2-types {{ qiime2_epoch }}.*
  - q2-feature-table {{ qiime2_epoch }}.*
  - q2-metadata {{ qiime2_epoch }}.*
  - q2-emperor {{ qiime2_epoch }}.*
  - q2-diversity-lib {{ qiime2_epoch }}.*
  - r-base {{ r_base }}
  - r-vegan >=2.5_3
  - umap-learn
  - numba
test:
  requires:
  - qiime2 >={{ qiime2 }}
  - q2templates >={{ q2templates }}
  - q2-types >={{ q2_types }}
  - q2-feature-table >={{ q2_feature_table }}
  - q2-metadata >={{ q2_metadata }}
  - q2-emperor >={{ q2_emperor }}
  - q2-diversity-lib >={{ q2_diversity_lib }}
  - pytest
  imports:
  - q2_diversity
  - qiime2.plugins.diversity
  commands:
  - py.test --pyargs q2_diversity
about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
